### ISSUE TITLE
an illegal memory access was encountered ？

### ISSUE THREAD

**Issue by Ferenas** [visinf/1-stage-wseg#13]
Hi，I am trying to run your code in my device, which only has one GPU v100. Therefore I changed your code about parallel calculating. I just modified few codes like this in train.py, line 81,82:
```
        self.enc.cuda()
        self.criterion_cls.cuda()
```
and put the image, gt_labels and img_raw in CUDA by adding the following codes in train,py : 
```
        image = image.cuda()
        image_raw = image_raw.cuda()
        gt_labels = gt_labels.cuda()
```
Then when I run the code I find the problem: 
```
Config: 
 {'NUM_GPUS': 1, 'TRAIN': {'BATCH_SIZE': 16, 'NUM_EPOCHS': 32, 'NUM_WORKERS': 8, 'MASK_LOSS': 0.0, 'PRETRAIN': 5}, 'TEST': {'METHOD': 'multiscale', 'DATA_ROOT': '/fastdata/naraslanov', 'SCALES': [1, 0.75, 1.25, 1.5], 'FLIP': True, 'PAD_SIZE': [768, 768], 'CROP_SIZE': [448, 448], 'CROP_GRID_SIZE': [2, 2], 'BATCH_SIZE': 8, 'BG_POW': 1, 'NUM_CLASSES': 21, 'USE_GT_LABELS': True, 'FP_CUT_SCORE': 0.3}, 'DATASET': {'CROP_SIZE': 448, 'SCALE_FROM': 0.9, 'SCALE_TO': 1.0, 'PATH': 'data/images'}, 'NET': {'MODEL': 'ae', 'BACKBONE': 'vgg16', 'PRE_WEIGHTS_PATH': './models/weights/vgg16_20M.pth', 'OPT': 'SGD', 'LR': 0.001, 'BETA1': 0.5, 'MOMENTUM': 0.9, 'WEIGHT_DECAY': 0.0005, 'LOSS': 'SoftMargin', 'MASK_LOSS_BCE': 1.0, 'BG_SCORE': 0.1, 'FOCAL_P': 3, 'FOCAL_LAMBDA': 0.01, 'PAMR_KERNEL': [1, 2, 4, 8, 12, 24], 'PAMR_ITER': 10, 'SG_PSI': 0.3}, 'MASKS': {'CRF': {'ALPHA_LOW': 4, 'ALPHA_HIGH': 32}}, 'CUDA': False, 'DEBUG': False, 'PYTORCH_VERSION_LESS_THAN_040': False}
Backbone: VGG16
Model: AE
Loading weights from:  ./models/weights/vgg16_20M.pth
Group 0: #13, LR=1.000e-03
Group 1: #13, LR=2.000e-03
Group 2: #26, LR=1.000e-02
Group 3: #13, LR=2.000e-02
Using SGD >>> learning rate = 1.000e-03, momentum = 9.000e-01, weight decay = 5.000e-04
Epoch >>>  0
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=700 : an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/amax/ZhangFei/1-stage-SS/train.py", line 340, in <module>
    time_call(trainer.validation, "Validation /   Val: ", epoch, trainer.writer_val, trainer.valloader, checkpoint=True)
  File "/home/amax/ZhangFei/1-stage-SS/train.py", line 329, in time_call
    func(*args, **kwargs)
  File "/home/amax/ZhangFei/1-stage-SS/train.py", line 253, in validation
    cls_raw, masks_all, mask_logits = eval_batch(image, gt_labels)
  File "/home/amax/ZhangFei/1-stage-SS/train.py", line 231, in eval_batch
    self.step(epoch, image, gt_labels, train=False, visualise=False)
  File "/home/amax/ZhangFei/1-stage-SS/train.py", line 101, in step
    losses = {"loss_cls": loss_cls.item(),
RuntimeError: CUDA error: an illegal memory access was encountered
```
However, when I run the orginal code in another device with 2 GPUs, it works well.. ,which means the data and label is fine. I don't know what's going on here

**Comment by arnike** [comment]
Hi @Ferenas,
were you able to resolve the issue? Provided enough memory on one GPU, the code should run without modification. You just need to specify the gpu ID with `CUDA_VISIBLE_DEVICES`.
Best,
Nikita

**Comment by Ferenas** [comment]
hi @arnike 
I have solved the problems, and
 I have to tell you it is the code error, in a line that u write as “+= 255”, which will cause the leak index of calculating loss , so I change it to the = 255, then everything works fine.
Btw, this is not an error of GPU, since I test the original parallel code with two GPUs and same problem is raised, so I have to read and understand ur code to solve the issue.

**Comment by DesertsP** [comment]
> hi @arnike
> I have solved the problems, and
> I have to tell you it is the code error, in a line that u write as “+= 255”, which will cause the leak index of calculating loss , so I change it to the = 255, then everything works fine.
> Btw, this is not an error of GPU, since I test the original parallel code with two GPUs and same problem is raised, so I have to read and understand ur code to solve the issue.

Hi @Ferenas 
Could you please provide more details about this problem? Which line  contains “+= 255”?

**Comment by Ferenas** [comment]
> > hi @arnike
> > I have solved the problems, and
> > I have to tell you it is the code error, in a line that u write as “+= 255”, which will cause the leak index of calculating loss , so I change it to the = 255, then everything works fine.
> > Btw, this is not an error of GPU, since I test the original parallel code with two GPUs and same problem is raised, so I have to read and understand ur code to solve the issue.
> 
> Hi @Ferenas
> Could you please provide more details about this problem? Which line contains “+= 255”?

Hi @DesertsP 
line 65, in stage_net.py ,
mask_gt += (1 - weight) * ignore_index
it is supposed to be:
mask_gt = (1 - weight) * ignore_index
since the aim of this code is to extract the points with low confidence and set their values to 255, so the following operation will ignore these points.

**Comment by arnike** [comment]
Hi @Ferenas,
thanks for your feedback. I do not think, however, that it's a correct solution. Replacing `+=` with `=` will also assign label 0 to all confident labels (`weight` is in [0, 1]).
@DesertsP, could you also provide some details of your setup? (GPUs and PyTorch version) I will try to reproduce this problem.
Thanks.

**Comment by DesertsP** [comment]
@arnike Yes. I re-install Pytorch 1.0, this issue disappeared. Higher version of Pytorch has this problem.

**Comment by Ferenas** [comment]
> Hi @Ferenas,
> thanks for your feedback. I do not think, however, that it's a correct solution. Replacing `+=` with `=` will also assign label 0 to all confident labels (`weight` is in [0, 1]).
> @DesertsP, could you also provide some details of your setup? (GPUs and PyTorch version) I will try to reproduce this problem.
> Thanks.

Hi @arnike,
Yes, you are right, I cancel the '+' because the weight valule is either 1 or 0 at the very begining of the training, then I thought it was a mistake to '+='. Thanks to the @DesertsP, it might be the pytorch version problems.

**Comment by crh19970307** [comment]
@arnike @DesertsP @Ferenas I have fix this bug just adding one line code. You can see it in https://github.com/visinf/1-stage-wseg/pull/15
